name: maps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  change_app_package_name: ^1.3.0
  flutter:
    sdk: flutter
   : ^7.0.2
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  location: ^7.0.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
